name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm ci

    - name: Build web app
      run: npm run build

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: gabai-release-apk
        path: android/app/build/outputs/apk/release/*.apk
        retention-days: 30

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: GabAi Beta v${{ github.run_number }}
        body: |
          🚀 **GabAi Beta Release**
          
          ## What's New in This Build:
          - ✅ Fixed affiliate link system - earning revenue from Amazon links
          - ✅ Database-persisted URL shortening
          - ✅ Voice-first AI assistant with OpenAI integration
          - ✅ Smart lists and calendar management
          - ✅ Native mobile notifications and alarms
          
          ## Installation:
          1. Download the APK file below
          2. Enable "Install from Unknown Sources" in Android settings
          3. Install and enjoy GabAi!
          
          **Subscription:** $14.95/month with 7-day free trial
        files: android/app/build/outputs/apk/release/*.apk
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}