name: Android APK Build 
 
on: 
  push: 
    branches: [ main ] 
  workflow_dispatch: 
 
jobs: 
  build-android: 
    runs-on: ubuntu-latest 
 
    steps: 
    - name: Checkout repository 
      uses: actions/checkout@v4 
 
    - name: Setup Node.js v20 
      uses: actions/setup-node@v4 
      with: 
        node-version: '20' 
        cache: 'npm' 
 
    - name: Verify Node.js version 
      run: node --version 
 
    - name: Setup Java 17 
      uses: actions/setup-java@v4 
      with: 
        distribution: 'temurin' 
        java-version: '17' 
 
    - name: Setup Android SDK 
      uses: android-actions/setup-android@v3 
 
    - name: Install Node dependencies 
      run: npm install 
 
    - name: Build web application 
      run: npx vite build 
 
    - name: Capacitor sync (requires Node 20+) 
      run: npx cap sync android 
 
    - name: Make Gradle wrapper executable 
      run: chmod +x android/gradlew 
 
    - name: Build Android APK 
      run: | 
        cd android 
        ./gradlew assembleDebug --no-daemon 
 
    - name: Upload APK artifact 
      uses: actions/upload-artifact@v4 
      with: 
        name: gabai-android-apk 
        path: android/app/build/outputs/apk/debug/app-debug.apk 
