name: Android CI (Production Ready)
on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-35
            build-tools;35.0.0

      - name: Install dependencies
        run: npm ci

      - name: Build web assets
        run: npm run build

      - name: Sync Capacitor to Android
        run: npx cap sync android

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Clean Android build
        working-directory: android
        run: ./gradlew clean

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug --stacktrace --no-daemon
        env:
          GRADLE_OPTS: "-Xmx3g -Dfile.encoding=UTF-8"

      - name: Build Release APK
        working-directory: android
        run: ./gradlew assembleRelease --stacktrace --no-daemon
        env:
          GRADLE_OPTS: "-Xmx3g -Dfile.encoding=UTF-8"

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: gabai-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: gabai-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 30

      - name: Verify APK files
        run: |
          echo "Debug APK size:"
          ls -lh android/app/build/outputs/apk/debug/app-debug.apk
          echo "Release APK size:"
          ls -lh android/app/build/outputs/apk/release/app-release.apk