name: 🛡️ Bulletproof APK Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools: 35.0.0
          
      - name: Install Dependencies
        run: npm ci --prefer-offline
        
      - name: Build Web Application
        run: npm run build
        
      - name: Sync Capacitor to Android
        run: npx cap sync android
        
      - name: Set Android SDK Path
        run: echo "sdk.dir=$ANDROID_HOME" > android/local.properties
        
      - name: Make gradlew executable
        run: chmod +x android/gradlew
        
      - name: Clean Android build
        working-directory: android
        run: ./gradlew clean --no-daemon --warning-mode=all
        
      - name: Check Android project health
        working-directory: android
        run: |
          ./gradlew help --no-daemon
          ./gradlew androidDependencies --no-daemon | head -10
          
      - name: Build Debug APK
        working-directory: android
        run: |
          ./gradlew assembleDebug \
            --no-daemon \
            --warning-mode=all \
            --stacktrace \
            -Dorg.gradle.jvmargs="-Xmx2g -XX:MaxMetaspaceSize=512m" \
            -Dfile.encoding=UTF-8
        env:
          GRADLE_OPTS: "-Xmx2g -Dfile.encoding=UTF-8"
          
      - name: Verify APK Creation
        run: |
          APK_PATH="android/app/build/outputs/apk/debug/app-debug.apk"
          if [ -f "$APK_PATH" ]; then
            echo "✅ APK created successfully!"
            ls -lh "$APK_PATH"
            file "$APK_PATH"
          else
            echo "❌ APK not found. Searching for APK files..."
            find android -name "*.apk" -type f || echo "No APK files found"
            exit 1
          fi
          
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: gabai-bulletproof-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 5