name: 📱 Cordova Simple APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Cordova
      run: |
        npm install -g cordova@12.0.0
        cordova --version

    - name: Create Cordova App
      run: |
        cordova create gabai-cordova com.gabai.app GabAi
        cd gabai-cordova
        cordova platform add android@12.0.0

    - name: Create App Content
      run: |
        cd gabai-cordova
        cat > www/index.html << 'EOF'
        <!DOCTYPE html>
        <html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GabAi</title>
        <style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:Arial,sans-serif;background:linear-gradient(135deg,#667eea,#764ba2);color:white;height:100vh;display:flex;align-items:center;justify-content:center;text-align:center}.container{max-width:400px;padding:20px}.logo{font-size:4em;margin-bottom:20px;animation:bounce 2s infinite}@keyframes bounce{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}h1{font-size:2.5em;margin-bottom:20px}.status{margin:20px 0;font-size:1.2em;animation:pulse 2s infinite}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.5}}.btn{background:rgba(255,255,255,.2);border:2px solid rgba(255,255,255,.3);color:white;padding:15px 30px;border-radius:50px;text-decoration:none;display:inline-block;margin:10px;transition:all .3s;cursor:pointer}.btn:hover{background:rgba(255,255,255,.3)}</style>
        </head><body><div class="container"><div class="logo">🤖</div><h1>GabAi</h1><div class="status" id="status">Starting GabAi...</div><button class="btn" onclick="launch()">Launch GabAi</button></div>
        <script>function launch(){window.open('https://gabai.ai','_system')}let count=3;const statusEl=document.getElementById('status');const timer=setInterval(()=>{statusEl.textContent='Launching in '+count+'...';count--;if(count<0){clearInterval(timer);launch()}},1500);document.addEventListener('deviceready',function(){console.log('Cordova ready')},false)</script>
        </body></html>
        EOF

    - name: Build APK
      run: |
        cd gabai-cordova
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        cordova build android --debug
        find platforms/android -name "*.apk" -exec cp {} ../gabai-cordova.apk \;

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: gabai-cordova-simple-apk
        path: gabai-cordova.apk

    - name: Build Summary
      run: |
        echo "✅ Cordova APK build complete" 
        echo "📱 File: gabai-cordova.apk"
        echo "🌐 Opens: https://gabai.ai"