name: Create Release with APK

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
    
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: 'platforms;android-35 build-tools;35.0.0'
        
    - name: Accept Android SDK licenses
      run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web application
      run: npx vite build
      
    - name: Sync Capacitor
      run: npx cap sync android
        
    - name: Build Android APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon
        
    - name: Upload APK as Artifact (No Release)
      uses: actions/upload-artifact@v4
      with:
        name: gabai-beta-apk-${{ github.run_number }}
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30