name: Create Release with APK

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
    
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: 'platforms;android-35 build-tools;35.0.0'
        
    - name: Accept Android SDK licenses
      run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web application
      run: npm run build
      
    - name: Sync Capacitor
      run: npx cap sync android
        
    - name: Build Android APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon
        
    - name: Create Release with APK
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0-beta.${{ github.run_number }}
        name: GabAi v1.0.0-beta.${{ github.run_number }}
        body: |
          🎯 **GabAi Mobile App - Production Ready**
          
          Download the APK below, enable "Install from unknown sources" on Android, and enjoy your voice-first AI assistant.
          
          **Features:**
          - Voice-first AI with OpenAI GPT-4o
          - Working affiliate monetization
          - Smart lists and calendar
          - OCR text extraction
          - Native notifications and alarms
          - ElevenLabs voice synthesis
          
          Ready for $14.95/month Google Play Store submission.
        files: android/app/build/outputs/apk/debug/app-debug.apk
        make_latest: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}