name: 🏆 Final APK Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools: 35.0.0
          
      - name: Install Dependencies & Build Web
        run: |
          npm ci
          npm run build
          
      - name: Configure Android Environment
        working-directory: android
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          chmod +x gradlew
          
      - name: Clean Build
        working-directory: android
        run: ./gradlew clean --no-daemon
        
      - name: Build Debug APK
        working-directory: android
        run: |
          ./gradlew assembleDebug --no-daemon --stacktrace
        env:
          GRADLE_OPTS: "-Xmx3g -Dfile.encoding=UTF-8"
          
      - name: Verify APK
        run: |
          APK_PATH="android/app/build/outputs/apk/debug/app-debug.apk"
          if [ -f "$APK_PATH" ]; then
            echo "✅ APK created successfully!"
            ls -lh "$APK_PATH"
            file "$APK_PATH"
          else
            echo "❌ APK not found"
            find android -name "*.apk" -type f || echo "No APK files found"
            exit 1
          fi
          
      - name: Upload Final APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: gabai-final-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7