name: Manual APK Build (Safe)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Java 17 (Required for Android)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Set JAVA_HOME Environment
      run: |
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
        echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm install

    - name: Build web application
      run: npx vite build

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Fix Capacitor Java Version (Override)
      run: |
        # Force Java 17 in all Capacitor generated files
        sed -i 's/JavaVersion.VERSION_21/JavaVersion.VERSION_17/g' android/app/capacitor.build.gradle
        echo "✅ Fixed Capacitor Java version to 17"
        
    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: gabai-manual-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk