name: Manual APK Build (Safe)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Java 17 (Force Consistent Environment)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Kill All Gradle Daemons and Reset Environment
      run: |
        # Kill any existing Gradle daemons with wrong Java version
        pkill -f gradle || true
        rm -rf ~/.gradle/daemon/ || true
        
        # Force consistent Java environment
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
        echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
        echo "GRADLE_OPTS=-Dorg.gradle.java.home=$JAVA_HOME -Dfile.encoding=UTF-8 -Dorg.gradle.daemon=false" >> $GITHUB_ENV
        echo "JAVA_OPTS=-Dfile.encoding=UTF-8" >> $GITHUB_ENV
        
        # Verify Java version
        java -version
        javac -version

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm install

    - name: Build web application
      run: npx vite build

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Embrace Java 21 Build Environment
      run: |
        # Set Java 21 environment variables
        export JAVA_OPTS="-Dfile.encoding=UTF-8"
        export GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx1536m -Dfile.encoding=UTF-8"
        
        echo "✅ Using Java 21 build environment - matching Capacitor defaults"
        
    - name: Nuclear Java 17 Override
      run: |
        echo "🔧 Nuclear Java 17 override - modifying all Capacitor source files..."
        
        # Find and replace ALL Java 21 references in Capacitor modules
        find node_modules/@capacitor -name "*.gradle" -type f -exec sed -i 's/JavaVersion\.VERSION_21/JavaVersion.VERSION_17/g' {} + 2>/dev/null || true
        find node_modules/@capacitor -name "*.gradle" -type f -exec sed -i 's/VERSION_21/VERSION_17/g' {} + 2>/dev/null || true
        find node_modules/@capacitor -name "*.gradle" -type f -exec sed -i 's/sourceCompatibility.*21/sourceCompatibility JavaVersion.VERSION_17/g' {} + 2>/dev/null || true
        find node_modules/@capacitor -name "*.gradle" -type f -exec sed -i 's/targetCompatibility.*21/targetCompatibility JavaVersion.VERSION_17/g' {} + 2>/dev/null || true
        
        # Force update the main Capacitor Android build file
        CAPACITOR_ANDROID_BUILD="node_modules/@capacitor/android/capacitor/build.gradle"
        if [ -f "$CAPACITOR_ANDROID_BUILD" ]; then
          echo "🔧 Patching main Capacitor Android build.gradle..."
          sed -i 's/JavaVersion\.VERSION_21/JavaVersion.VERSION_17/g' "$CAPACITOR_ANDROID_BUILD"
          sed -i 's/VERSION_21/VERSION_17/g' "$CAPACITOR_ANDROID_BUILD"
          sed -i 's/compileOptions {/compileOptions {\n        sourceCompatibility JavaVersion.VERSION_17\n        targetCompatibility JavaVersion.VERSION_17/g' "$CAPACITOR_ANDROID_BUILD"
        fi
        
        # Update core Capacitor module
        CAPACITOR_CORE_BUILD="node_modules/@capacitor/android/capacitor-android/build.gradle"
        if [ -f "$CAPACITOR_CORE_BUILD" ]; then
          echo "🔧 Patching Capacitor core Android build.gradle..."
          sed -i 's/JavaVersion\.VERSION_21/JavaVersion.VERSION_17/g' "$CAPACITOR_CORE_BUILD"
          sed -i 's/VERSION_21/VERSION_17/g' "$CAPACITOR_CORE_BUILD"
        fi
        
        # Re-sync after modifications
        npx cap sync android --force
        
        cd android
        chmod +x gradlew
        
        echo "🔧 Modified Capacitor source files for Java 17 compatibility"
        echo "🔧 Building APK with patched Capacitor modules..."
        
        # Clean build with maximum isolation
        ./gradlew clean --no-daemon --no-build-cache
        
        # Build with detailed error reporting
        ./gradlew assembleDebug \
          --no-daemon \
          --no-build-cache \
          --no-configuration-cache \
          --stacktrace \
          --info

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: gabai-manual-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk