name: 🎯 Minimal APK Build
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: npm
    
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build web assets
      run: npm run build
    
    - name: Sync Capacitor
      run: npx cap sync android --no-open
    
    - name: Fix Android permissions
      run: |
        chmod +x android/gradlew
        find android -name "*.gradle" -exec chmod 644 {} \;
    
    - name: Clean and build APK (simplified)
      working-directory: android
      run: |
        # Simple clean and build without daemon
        rm -rf .gradle build */build
        ./gradlew clean assembleDebug --no-daemon --no-build-cache --no-configuration-cache
      env:
        GRADLE_OPTS: "-Xmx2g -Dfile.encoding=UTF-8"
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: gabai-minimal-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7