name: ☢️ Nuclear Java 17 Fix
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Setup Java 17
        uses: actions/setup-java@v4  
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools: 35.0.0
          
      - name: Install Dependencies & Build Web
        run: |
          npm ci
          npm run build
          
      - name: Capacitor Sync
        run: npx cap sync android
        
      - name: Nuclear Java 17 Enforcement
        run: |
          cd android
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          
          # Force Java 17 in EVERY gradle file
          find . -name "*.gradle" -type f -exec sed -i 's/VERSION_21/VERSION_17/g' {} \;
          find . -name "*.gradle" -type f -exec sed -i 's/languageVersion.*21/languageVersion = JavaLanguageVersion.of(17)/g' {} \;
          find . -name "*.gradle" -type f -exec sed -i 's/jvmTarget.*21/jvmTarget = '\''17'\''/g' {} \;
          
          # Add global Java 17 toolchain to root build.gradle  
          cat << 'EOF' >> build.gradle
          
          // NUCLEAR OPTION: Force Java 17 everywhere
          gradle.projectsEvaluated {
              allprojects {
                  plugins.withType(JavaPlugin) {
                      java {
                          toolchain {
                              languageVersion = JavaLanguageVersion.of(17)
                          }
                      }
                  }
                  afterEvaluate {
                      if (hasProperty('android')) {
                          android {
                              compileOptions {
                                  sourceCompatibility JavaVersion.VERSION_17
                                  targetCompatibility JavaVersion.VERSION_17
                              }
                          }
                      }
                  }
              }
          }
          EOF
          
          # Force Java 17 in gradle.properties
          echo "org.gradle.java.home=$JAVA_HOME" >> gradle.properties
          echo "org.gradle.java.installations.auto-detect=false" >> gradle.properties
          
          chmod +x gradlew
          
      - name: Debug Build Configuration
        working-directory: android
        run: |
          echo "=== Java Home: $JAVA_HOME ==="
          echo "=== Java Version ==="
          java -version
          echo "=== Modified Build Files ==="
          find . -name "*.gradle" -type f -exec echo "=== {} ===" \; -exec head -10 {} \;
          
      - name: Clean & Build
        working-directory: android
        run: |
          ./gradlew clean --no-daemon
          ./gradlew assembleDebug --no-daemon --warning-mode=all
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          GRADLE_OPTS: "-Xmx2g -Dorg.gradle.java.home=${{ env.JAVA_HOME }} -Dfile.encoding=UTF-8"
          
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: gabai-nuclear-fix
          path: android/app/build/outputs/apk/debug/app-debug.apk