name: Simple APK Build
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Setup Capacitor
      run: |
        npx cap sync android
        
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug --no-daemon
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: gabai-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0-beta-${{ github.run_number }}
        name: GabAi Beta v1.0-${{ github.run_number }}
        files: android/app/build/outputs/apk/debug/app-debug.apk
        body: |
          # GabAi Beta Release
          
          ## New Features
          - Currency calculation system with Payment Schedule & Budget Tracker
          - Real-time dollar amount validation and totaling
          - Native Android experience (no browser bar)
          - Enhanced smart lists with drag-and-drop reordering
          
          ## Download Instructions
          1. Download the APK file below
          2. Enable "Unknown Sources" in Android settings
          3. Install the APK
          4. Enjoy the native app experience!
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}