name: Ultimate Node 20 Fix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Remove existing Node completely
      run: |
        sudo rm -rf /usr/local/bin/node || true
        sudo rm -rf /usr/local/bin/npm || true
        sudo rm -rf /usr/local/lib/node_modules || true
        sudo rm -rf /opt/hostedtoolcache/node || true
    
    - name: Install Node.js 20 directly from NodeSource
      run: |
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y nodejs
        
    - name: Verify Node installation
      run: |
        node --version
        npm --version
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: npm install
      
    - name: Build web application
      run: npx vite build
      
    - name: Sync Capacitor Android
      run: npx cap sync android
        
    - name: Build Android APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: gabai-ultimate-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk