name: 🚀 Ultra Simple APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Manual Android SDK Setup
      run: |
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-12266719_latest.zip
        unzip -q commandlinetools-linux-12266719_latest.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/ 2>/dev/null || true
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        yes | sdkmanager --licenses
        sdkmanager "platforms;android-33" "build-tools;33.0.2"

    - name: Create Simple APK Project
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/build-tools/33.0.2
        mkdir -p gabai/app/src/main/java/com/gabai/app
        mkdir -p gabai/app/src/main/res/values
        mkdir -p gabai/app/src/main/assets/www
        cd gabai

    - name: Create App Files
      run: |
        cd gabai
        
        # HTML File
        cat > app/src/main/assets/www/index.html << 'EOF'
        <!DOCTYPE html>
        <html><head><meta charset="UTF-8"><title>GabAi</title>
        <style>body{margin:0;background:linear-gradient(135deg,#667eea,#764ba2);color:white;text-align:center;font-family:Arial,sans-serif;height:100vh;display:flex;align-items:center;justify-content:center}.container{max-width:400px}.logo{font-size:4em;margin-bottom:20px;animation:bounce 2s infinite}@keyframes bounce{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}h1{font-size:2.5em;margin-bottom:20px}.status{margin:20px 0;animation:pulse 2s infinite}@keyframes pulse{0%,100%{opacity:1}50%{opacity:.5}}.btn{background:rgba(255,255,255,.2);border:2px solid rgba(255,255,255,.3);color:white;padding:15px 30px;border-radius:50px;text-decoration:none;display:inline-block;margin:10px;transition:all .3s}</style>
        </head><body><div class="container"><div class="logo">🤖</div><h1>GabAi</h1><div class="status" id="status">Starting GabAi...</div><a href="https://gabai.ai" class="btn" onclick="launch()">Launch GabAi</a></div>
        <script>function launch(){window.location.href='https://gabai.ai'}let count=3;const statusEl=document.getElementById('status');const timer=setInterval(()=>{statusEl.textContent='Opening in '+count+'...';count--;if(count<0){clearInterval(timer);launch()}},1500)</script></body></html>
        EOF
        
        # Android Manifest
        cat > app/src/main/AndroidManifest.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.gabai.app">
            <uses-permission android:name="android.permission.INTERNET" />
            <application android:label="GabAi" android:theme="@android:style/Theme.NoTitleBar.Fullscreen">
                <activity android:name=".MainActivity" android:exported="true">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>
        </manifest>
        EOF
        
        # MainActivity
        cat > app/src/main/java/com/gabai/app/MainActivity.java << 'EOF'
        package com.gabai.app;
        import android.app.Activity;
        import android.os.Bundle;
        import android.webkit.WebView;
        public class MainActivity extends Activity {
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                WebView webView = new WebView(this);
                webView.getSettings().setJavaScriptEnabled(true);
                webView.loadUrl("file:///android_asset/www/index.html");
                setContentView(webView);
            }
        }
        EOF
        
        # Resources
        echo '<resources><string name="app_name">GabAi</string></resources>' > app/src/main/res/values/strings.xml

    - name: Create Build Configuration
      run: |
        cd gabai
        
        # Root build.gradle
        cat > build.gradle << 'EOF'
        buildscript {
            repositories { google(); mavenCentral() }
            dependencies { classpath 'com.android.tools.build:gradle:8.2.2' }
        }
        allprojects { repositories { google(); mavenCentral() } }
        EOF
        
        # App build.gradle  
        cat > app/build.gradle << 'EOF'
        plugins { id 'com.android.application' }
        android {
            namespace 'com.gabai.app'
            compileSdk 33
            defaultConfig {
                applicationId "com.gabai.app"
                minSdk 21
                targetSdk 33
                versionCode 1
                versionName "1.0"
            }
        }
        EOF
        
        # Settings and properties
        echo "include ':app'" > settings.gradle
        echo 'org.gradle.jvmargs=-Xmx2g' > gradle.properties
        echo 'android.useAndroidX=true' >> gradle.properties

    - name: Build APK with Gradle Wrapper
      run: |
        cd gabai
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/build-tools/33.0.2
        
        # Initialize Gradle wrapper
        gradle wrapper --gradle-version 8.5
        chmod +x gradlew
        
        # Build APK
        ./gradlew assembleDebug --no-daemon --stacktrace
        
        # Find and copy APK
        find . -name "app-debug.apk" -exec cp {} ../gabai-ultra.apk \;
        ls -la ../gabai-ultra.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: gabai-ultra-apk
        path: gabai-ultra.apk
        retention-days: 30

    - name: Build Summary
      run: |
        echo "✅ Ultra Simple APK Complete"
        echo "📱 File: gabai-ultra.apk" 
        echo "🌐 Redirects to: https://gabai.ai"
        echo "⚡ Manual SDK setup bypassed all compatibility issues"